version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/base:stable

commands:
  docker_base_prep:
    description: "Checkout, docker build & login"
    steps:
      - checkout
      # For more information on what this special docker step does, see:
      #   https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker
      - run:
          name: Enable Docker CLI experimental features
          command: echo 'export DOCKER_CLI_EXPERIMENTAL=enabled' >> $BASH_ENV
      - run:
          name: Configure multi-arch builder
          command: |
            # Registers binfmt for ARM support when doing multi-arch builds
            # For more information, see https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/
            docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
            # Creates and uses the multi-arch builder, as default
            # builder doesn't allow for multi-arch builds
            docker context create node-multiarchbuilder
            docker buildx create --use --name multiarchbuilder node-multiarchbuilder
      - run:
          name: List supported architecture for multi-arch builder
          command: docker buildx inspect --bootstrap
      - run:
          name: Validate docker-compose setup
          command: docker-compose -f "docker-compose.yml" -f "docker-compose.local.yml" build

jobs:
  build-master:
    <<: *defaults

    steps:
      - docker_base_prep
      - run:
          name: Build & push Shinobi as latest multi-arch docker image
          command: |
            echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
            cd shinobi
            # Build with multi-arch build, with logging set to 'plain'
            # to avoid logging issues with the CI service.
            docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 -t "$DOCKER_REGISTRY_USER/shinobi:latest" --progress plain --push .

  build:
    <<: *defaults

    steps:
      - docker_base_prep
      - run:
          name: Build & push Shinobi as multi-arch docker image
          command: |
            echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
            cd shinobi
            docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 -t "$DOCKER_REGISTRY_USER/shinobi:$CIRCLE_SHA1" --progress plain --push .

workflows:
  version: 2
  build-publish:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - build:
          filters:
            branches:
              ignore:
                - master